version: '3'
services:
  owltech-vite-app:
    container_name: owltech-vite-app
    build: .
    restart: always
    ports:
      - "5173:5173"
  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=santiveraespinoza@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - owltech-vite-app

volumes:
  nginx_secrets: